export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const REMOVE = 'REMOVE';
export const ON_SUBMIT_REVIEW = 'ON_SUBMIT_REVIEW';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';

